### ISSUE TITLE
Zio Payload Move Gimbal Speed

### ISSUE THREAD

**Issue by andrefreitas97** [Gremsy/Payload-Assistant-App#1]
Hello.

I am using a Zio Payload and started to test this app.

The problem I noticed is the fact that when I use the "Move Gimbal" section, the movement speed can only be increased to 10 deg/s which is too slow and besides this the gimbal seems to not even be rotating at this speed. To go from 0 degrees pitch to -90 degrees it takes more than 30 seconds.

If someone could help me with this problem I would be very grateful.

**Comment by gremsyQuanLe** [comment]
Hello !

You can try https://github.com/Gremsy/Payload-Assistant-App/releases/tag/v1.2.3 and use the "Move Gimbal"
